name: adb_tools_tab_apps
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  adb_tools_interface:
    path: ../adb_tools_interface
  provider: ^6.1.1
  logging: ^1.2.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
